name: Java Maven CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package
